[tool.black]
line-length = 79

[tool.pytest.ini_options]
# to see log output when running tests, set log_cli = true
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
